### ISSUE TITLE
Fails to build with OpenSSL 1.1

### ISSUE THREAD

**Issue by hrw** [quantcast/qfs#226]
I wanted to build qfs under Debian 9 'stretch' and failed.

qfs needs changes to work with OpenSSL 1.1

**Comment by mikeov** [comment]
Marcin,

I’ve added Travis Debian 9 build:

https://travis-ci.org/quantcast/qfs/jobs/308803467

On Debian 9 compiler emitted warning (fixed by https://github.com/quantcast/qfs/commit/b53f9ef5968499c3d177a8bf8774f082cf749196). Without this change the build succeeded, unless -Werror compiler flag was set.

— Mike.
