### ISSUE TITLE
qfs-metaserver unable to start up

### ISSUE THREAD

**Issue by mchybo** [quantcast/qfs#62]
Due to metaserver machine failure we had to restart whole QFS cluster. Unfortunately, metaserver is unable to check all chunks properly due to chunkservers' failure to re-check all chunk directories.
Each chunkserver log contains lots of entries like:
```
failed to open chunk file: /path_to_qfs_chunk_dir/18636013.11249341.1 :Success 0 out of requests
```
How can I get my cluster back up and running? I need to access data stored in it ASAP.

**Comment by fsareshwala** [comment]
Hi there,

I sincerely apologize for the late response. Quantcast has been working hard to staff up its QFS team so that we can appropriately engage the community and answer any questions. Our failure to respond to you in time is very embarrassing and I am truly sorry for that.

I'm not sure if you are still having this problem so I am going to close out this request. However, I would still like to help as much as possible. If you are still having this problem, could you post more of your logs so that we can take a look into what happened?
