### ISSUE TITLE
Data locality question

### ISSUE THREAD

**Issue by chanwit** [quantcast/qfs#68]
We are evaluating to adopt QFS to replace HDFS for our Apache Spark stack, but one of our engineers has googled and found a paper saying that QFS is abandoned data locality by design.

I think I can understand this as 6+3 Reed-Solomon does not give a *full* 100% data locality.
To my understanding, it should at least be 66% data locality when reading data through a HDFS client.

Correct me if I am wrong. Thank you!

**Comment by panfengfeng** [comment]
In my opinion, the data locality is 1/6 (max)

在 16/12/2015 9:54 PM, Chanwit Kaewkasi 写道:
>
> We are evaluating to adopt QFS to replace HDFS for our Apache Spark 
> stack, but one of our engineers has googled and found a paper saying 
> that QFS is abandoned data locality by design.
>
> I think I can understand this as 6+3 Reed-Solomon does not give a 
> /full/ 100% data locality.
> To my understanding, it should at least be 66% data locality when 
> reading data through a HDFS client?
> Am I correct?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/quantcast/qfs/issues/68>.
>

-- 

Best Regards !

*PanFengfeng

*

State Key Laboratory of Computer Architecture,

Institute of Computing Technology,

Chinese Academy of Sciences

Address:

1005D,No 6. Kexueyuan South Road

Haidian District, Beijing, China, 100190

Email:

panfengfeng@ict.ac.cn <mailto:panfengfeng@ict.ac.cn> or 
panfengfeng@ncic.ac.cn <mailto:panfengfeng@ncic.ac.cn>

**Comment by chanwit** [comment]
@panfengfeng could you elaborate more why is it max at only 1/6?

**Comment by chanwit** [comment]
I have more understanding now that its stripe-based makes data locality low and it relies on the assumption of fast network.

**Comment by fsareshwala** [comment]
Apologies for the late response. QFS has indeed abandoned data locality and instead optimizes for storage efficiency. Network performance has vastly outperformed disk performance in recent years and the assumptions made when HDFS was first written to bring the computation to the data don't necessarily hold true any longer.

To answer your question regarding data locality, a file in QFS will be split into 6 data chunks and 3 parity chunks. The best you will get in terms of data locality is a single chunk is readily available on the local filesystem. It doesn't matter if you are accessing QFS through an HDFS client since the QFS client code is actually running underneath.

QFS offers data storage optimizations over HDFS in that you use 50% less data when using Reed-Solomon encoding. However, in order to get that, you do give up some data locality. Networks these days are way faster than disks so that should be okay.
